apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-static-alpine1
spec:
  config: '{
   "cniVersion": "0.3.0",
   "type": "macvlan",
   "master": "ens16",
   "mode": "bridge",
   "ipam": {
     "type": "static",
     "addresses": [
       {
         "address": "10.1.0.11/24"
       },
       {
         "address": "fd10::11/64"
       }
     ]
  }
 }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-static-alpine2
spec:
  config: '{
   "cniVersion": "0.3.0",
   "type": "macvlan",
   "master": "ens16",
   "mode": "bridge",
   "ipam": {
     "type": "static",
     "addresses": [
       {
         "address": "10.1.0.12/24"
       },
       {
         "address": "fd10::12/64"
       }
     ]
  }
 }'
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine1
  annotations:
    k8s.v1.cni.cncf.io/networks: default/macvlan-static-alpine1
spec:
  nodeSelector:
    kubernetes.io/hostname: m1
  containers:
    - image: alpine
      command: ["/bin/ash"]
      args: ["-c", "apk add iperf3; iperf3 -s"]
      imagePullPolicy: IfNotPresent
      name: alpine
      securityContext:
        privileged: true
        runAsUser: 0
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine2
  annotations:
    k8s.v1.cni.cncf.io/networks: default/macvlan-static-alpine2
spec:
  nodeSelector:
    kubernetes.io/hostname: m2
  containers:
    - image: alpine
      command: ["/bin/ash"]
      args: ["-c", "apk add iperf3; iperf3 -s"]
      imagePullPolicy: IfNotPresent
      name: alpine
      securityContext:
        privileged: true
        runAsUser: 0
