apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-w1-ens16f0
spec:
  config: '{
   "cniVersion": "0.3.0",
   "type": "macvlan",
   "master": "ens16f0",
   "mode": "bridge",
   "ipam": {
     "type": "host-local",
     "ranges": [
       [
         {
           "subnet": "10.1.10.0/24",
           "rangeStart": "10.1.10.20",
           "rangeEnd": "10.1.10.29"
         }
       ],
       [
         {
           "subnet": "fd10::/64",
           "rangeStart": "fd10::20",
           "rangeEnd": "fd10::29"
         }
       ]
     ]
   }
 }'
