apiVersion: v1
kind: Pod
metadata:
  name: prep-m1
  annotations:
spec:
  nodeSelector:
    kubernetes.io/hostname: m1
  hostNetwork: true
#  restartPolicy: Never
  containers:
    - image: alpine
      command: ["/bin/ash"]
      args: ["-c", "apk add pciutils tcpdump iperf3; lspci|grep Eth; ifconfig ens16 up; sleep infinity"]
      imagePullPolicy: IfNotPresent
      name: alpine
      securityContext:
        privileged: true
        runAsUser: 0
---
apiVersion: v1
kind: Pod
metadata:
  name: prep-m2
  annotations:
spec:
  nodeSelector:
    kubernetes.io/hostname: m2
  hostNetwork: true
#  restartPolicy: Never
  containers:
    - image: alpine
      command: ["/bin/ash"]
      args: ["-c", "apk add pciutils tcpdump iperf3; lspci|grep Eth; ifconfig ens16 up; sleep infinity"]
      imagePullPolicy: IfNotPresent
      name: alpine
      securityContext:
        privileged: true
        runAsUser: 0
          #  restartPolicy: Never

