apiVersion: v1
kind: Pod
metadata:
  name: prep-w0
  annotations:
spec:
  nodeSelector:
    kubernetes.io/hostname: w0
  hostNetwork: true
#  restartPolicy: Never
  containers:
    - image: alpine
      command: ["/bin/ash"]
      args: ["-c", "apk add pciutils tcpdump iperf3; lspci|grep Eth; ifconfig ens16f0 up; sleep infinity"]
      imagePullPolicy: IfNotPresent
      name: alpine
      securityContext:
        privileged: true
        runAsUser: 0
---
apiVersion: v1
kind: Pod
metadata:
  name: prep-w1
  annotations:
spec:
  nodeSelector:
    kubernetes.io/hostname: w1
  hostNetwork: true
#  restartPolicy: Never
  containers:
    - image: alpine
      command: ["/bin/ash"]
      args: ["-c", "apk add pciutils tcpdump iperf3; lspci|grep Eth; ifconfig ens16f0 up; sleep infinity"]
      imagePullPolicy: IfNotPresent
      name: alpine
      securityContext:
        privileged: true
        runAsUser: 0
          #  restartPolicy: Never

